### ISSUE TITLE
Plugin crash OBS Studio FTL on startup

### ISSUE THREAD

**Issue by z4kk** [Palakis/obs-websocket#57] opened 2017-04-01 09:13 UTC
I have problems with running obs-websocket in [OBS Studio FTL](https://github.com/WatchBeam/obs-studio-ftl/releases)

After plugin installation OBS does not starting. In Event log I see that record: 
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" />
        <EventID Qualifiers="0">1000</EventID>
        <Level>2</Level>
        <Task>100</Task>
        <Keywords>0x80000000000000</Keywords>
        <TimeCreated SystemTime="2017-04-01T09:04:08.659185700Z" />
        <EventRecordID>153858</EventRecordID>
        <Channel>Application</Channel>
        <Computer>DevStudio</Computer>
        <Security />
    </System>
    <EventData>
        <Data>obs64.exe</Data>
        <Data>0.0.0.0</Data>
        <Data>58d29914</Data>
        <Data>ucrtbase.dll</Data>
        <Data>10.0.14393.0</Data>
        <Data>578997b5</Data>
        <Data>c0000409</Data>
        <Data>000000000006ea1e</Data>
        <Data>52b0</Data>
        <Data>01d2aac6eb07e641</Data>
        <Data>C:\Program Files (x86)\OBS Studio - FTL\bin\64bit\obs64.exe</Data>
        <Data>C:\WINDOWS\System32\ucrtbase.dll</Data>
        <Data>9935b9b7-80c0-45f6-a1d2-b0d34d92212f</Data>
        <Data />
        <Data />
    </EventData>
</Event>
```

**Comment by WizardCM** [comment] 2017-04-01 09:20
Duplicate of #31 - it's their end.

**Comment by Palakis** [comment] 2017-04-01 22:59
I'm closing this ticket, as this issue depends on the folks of OBS FTL.

**Closed by Palakis** 2017-04-01 22:59 UTC
