### ISSUE TITLE
ScenesChanged - reordered

### ISSUE THREAD

**Issue by CVHvisuals** [Palakis/obs-websocket#537] opened 2020-06-10 16:33 UTC
// Feature request
ScenesChanged - Scenes have been **reordered**

//Description
ScenesChanged
The scene list has been modified. Scenes have been added, removed, or renamed.

**Comment by CVHvisuals** [comment] 2020-06-10 23:04
It doesn’t seem to be working for me on

macOS 10.15.5
Windows 10

obs-websocket 4.8

Can you confirm?

**Comment by tt2468** [comment] 2020-07-08 04:49
The documentation does not say that it emits the event when the scenes are reordered. I can confirm that it does not emit the event on reorder.

Unfortunately, after digging into the OBS UI code, there does not appear to be an event signal for the scenes getting reordered, so we can't really help there. Closing this now since technically everything is functioning properly.

**Closed by tt2468** 2020-07-08 04:49 UTC
