### ISSUE TITLE
Feature request: Add in protocol Swap PVW PGM

### ISSUE THREAD

**Issue by DeeJayMX** [Palakis/obs-websocket#344] opened 2019-06-15 17:21 UTC
Please add the ability to enable/disable the swap source function on Preview and program output
![SwapSource](https://user-images.githubusercontent.com/36418772/59554418-ca1ec980-8fa2-11e9-9eac-1c27c804d535.png)

**Comment by Palakis** [comment] 2019-08-26 22:36
Duplicate of  #187

**Closed** 2019-08-26 22:37 UTC
Labels: duplicate
