### ISSUE TITLE
Websocket causing OBS to hang on thread wait.

### ISSUE THREAD

**Issue by Grid21** [Palakis/obs-websocket#615] opened 2020-11-19 07:33 UTC
##### Description
I have been having an issue where OBS Studio has been crashing while the OBS Websocket has been enabled. According to the OBS devs themselves, somehow Websocket is doing a "hang on thread" action that's causing the program to "enter a sleep state". I don't know the whole technical part of it. But as I spoke with the OBS devs directly, that's what has been happening.

##### Steps to reproduce and other useful info
I can reproduce it by simply having Websocket run, but if I disable it, OBS is fine. I am using WebSocket to connect to a 3rd part program called Lorian board that allows my viewers to interact with my OBS Studio. My obs logs don't reflect this issue but I have a dump file I can provide.
[https://drive.google.com/file/d/1QG9rIy814Sb7sRGtI8kpfE86eQ2QNdhC/view?usp=sharing](OBS Dump file)

##### Technical information
- Windows 10 Pro 64-bit :
- OBS Studio Version 26.0.2
- I don't know the version, but it was the last version to be released a few years ago.

**Comment by tt2468** [comment] 2021-02-02 14:47
This should now be fixed in #644

I'm keeping #645 open for now in case anyone has any further comments about it.

**Comment by Grid21** [comment] 2021-02-02 19:24
> This should now be fixed in #644
> 
> I'm keeping #645 open for now in case anyone has any further comments about it.

Ok, I have this issue of OBS either outright crashing during a stream when OBS WebSocket is enabled, or it will crash when I hit exit on OBS After I am done a stream. It's pretty serious since I rely on Websocket for some functions and I am growing concerned this issue won't be fixed at all or a new update pushed out.

**Comment by tt2468** [comment] 2021-02-02 19:45
Interesting crash dump. My WinDbg shows the crash being caused by `obs_module_ver`, but we do not even have that function implemented.

```STACK_TEXT:  
000000d1`5aaf9818 00007ffb`881cfc21     : 000000d1`5aaf98d8 00007ffb`881e3f70 0000041f`4d8672cb 000000d1`5aaf9890 : ntdll!NtDelayExecution+0x14
000000d1`5aaf9820 00007ffb`721a2c5c     : 000000d1`5aaf9938 00007ffb`00000000 000000d1`c00000bb 00000000`00000000 : KERNELBASE!SleepEx+0xa1
000000d1`5aaf98c0 00007ffb`4dfce901     : 00000000`00989680 00000232`dcc02e60 000000d1`5aaf99d0 00007ffb`721a356f : msvcp140!_Thrd_sleep+0x3c
000000d1`5aaf9910 00007ffb`4dfce861     : 00000000`00989680 00000232`c1dc2d20 00000000`00000001 000000d1`5aaf9a29 : obs_websocket!obs_module_ver+0x1bfde
000000d1`5aaf9960 00007ffb`4e00df9a     : 00019c3a`4893e408 00000232`dcbf3000 00000232`dcbf3000 00000232`dcbf6b80 : obs_websocket!obs_module_ver+0x1bf3e
000000d1`5aaf9990 00007ffb`4e032d87     : 00000232`dc7b4ae0 00000232`dc76a320 00000000`0000002c 00000000`ffffffff : obs_websocket!obs_module_ver+0x5b677
000000d1`5aaf9a90 00007ffb`361ce33e     : 00000232`cb7e2c40 00000000`00000001 00007ffb`36563cc8 00000232`dcbf4b00 : obs_websocket!obs_module_ver+0x80464
000000d1`5aaf9b00 00007ffb`51152289     : 00000232`dcbf4b00 00000232`00000008 00000000`00000000 00000000`00000024 : Qt5Core!QMetaObject::activate+0x4fe
000000d1`5aaf9c20 00007ffb`361ce41a     : 000000d1`5aaf9d29 00007ffb`511520f0 00007ffb`36563f68 00000000`00000004 : Qt5Widgets!QDialogButtonBox::qt_static_metacall+0x199
000000d1`5aaf9c70 00007ffb`510b9397     : 00000232`dcbf3d40 00000232`00000009 00000232`dc76b080 00000232`00000008 : Qt5Core!QMetaObject::activate+0x5da
000000d1`5aaf9d90 00007ffb`510b92c1     : 00000232`dc76b000 00000232`dc76b080 00000232`dcbf3d40 00000014`00000035 : Qt5Widgets!QAbstractButton::clicked+0xa7
000000d1`5aaf9dd0 00007ffb`510b9fcc     : 00007ffb`50fc0000 000000d1`5aaf9f30 000000d1`5aafac70 00000233`521bd6e0 : Qt5Widgets!QAbstractButton::click+0x191
000000d1`5aaf9e00 00007ffb`50ffd0c7     : 00000013`00000019 00007ffb`50fc0000 000000d1`5aafac70 00000232`dcbf3d40 : Qt5Widgets!QAbstractButton::mouseReleaseEvent+0x8c
000000d1`5aaf9e30 00007ffb`50fd890d     : 00000232`d22de330 00000232`d22de330 00000232`dcbf3d40 000000d1`5aafac70 : Qt5Widgets!QWidget::event+0xe7
000000d1`5aafa180 00007ffb`50fd6419     : 00000232`dcbf3d40 000000d1`5aafa2b0 000000d1`5aafac70 00000000`00000000 : Qt5Widgets!QApplicationPrivate::notify_helper+0x17d
000000d1`5aafa1b0 00007ffb`361ac2c9     : 00000232`dcbf3d40 00000232`dcbf3d40 000000d1`5aafac70 00000232`dc76b080 : Qt5Widgets!QApplication::notify+0x7f9
000000d1`5aafa8a0 00007ffb`50fd9f53     : 00000000`00000000 00000232`ac4192e0 00007ffb`514da318 00000000`00000000 : Qt5Core!QCoreApplication::notifyInternal2+0xb9
000000d1`5aafa920 00007ffb`51028689     : 00000232`dcbf3d40 000000d1`5aafb910 00000000`00000001 000000d1`5aafaa00 : Qt5Widgets!QApplicationPrivate::sendMouseEvent+0x3f3
000000d1`5aafa9f0 00007ffb`51026348     : 00000232`ac4192e0 00000232`ac4192e0 00000232`dcbf3d40 00000232`dcbf3d40 : Qt5Widgets!QSizePolicy::QSizePolicy+0x2ee9
000000d1`5aafad90 00007ffb`50fd890d     : 00000232`d22de330 00000232`d22c9010 00000232`ac4192e0 000000d1`5aafb8e0 : Qt5Widgets!QSizePolicy::QSizePolicy+0xba8
000000d1`5aafaee0 00007ffb`50fd7767     : 00000232`d22de330 000000d1`5aafb010 000000d1`5aafb8e0 00000232`d22c9010 : Qt5Widgets!QApplicationPrivate::notify_helper+0x17d
000000d1`5aafaf10 00007ffb`361ac2c9     : 00000000`00000000 00000232`ac4192e0 000000d1`5aafb8e0 00000000`000d1d90 : Qt5Widgets!QApplication::notify+0x1b47
000000d1`5aafb600 00007ffb`4ffc0557     : 00000000`00000003 00000000`00000107 00000000`00000003 00000000`00000000 : Qt5Core!QCoreApplication::notifyInternal2+0xb9
000000d1`5aafb680 00007ffb`4ffa4d3d     : 00000232`91fd9690 00000000`00000000 00000000`00000000 00000232`00000107 : Qt5Gui!QGuiApplicationPrivate::processMouseEvent+0x6f7
000000d1`5aafbad0 00007ffb`361f82e6     : 00000232`d22ea8c0 00000000`00000000 00007ffb`503b4aa0 00007ffb`503b4aa0 : Qt5Gui!QWindowSystemInterface::sendWindowSystemEvents+0x1cd
000000d1`5aafbb40 00007ffb`8a0c5c7d     : 00000000`0089115e 00007ffb`8a0d20d3 00000000`00000001 00000000`00000001 : Qt5Core!QEventDispatcherWin32::processEvents+0xce6
000000d1`5aafbc80 00007ffb`8a0c5672     : 00000232`d2999a60 00007ffb`361f7ef0 00000000`00e80d68 000000d1`5aafbec8 : user32!UserCallWinProcCheckWow+0x2bd
000000d1`5aafbe10 00007ffb`361f7baf     : 00007ffb`361f7ef0 00000000`00000001 00000232`d22ea9b8 00000232`d22ea900 : user32!DispatchMessageWorker+0x1e2
000000d1`5aafbe90 00007ffb`6afaaa69     : 00007ff7`f6699201 00000000`00000000 00000232`d22de300 00000232`abf94600 : Qt5Core!QEventDispatcherWin32::processEvents+0x5af
000000d1`5aaff010 00007ffb`361a7442     : 00000000`00000000 000000d1`00000014 00000232`abf946c0 00000232`d22af6d0 : qwindows!qt_plugin_query_metadata+0x1b39
000000d1`5aaff040 00007ffb`361aab3a     : 00000232`d2295130 00000000`00000000 000000d1`5aaff5c0 00007ffb`362a7f98 : Qt5Core!QEventLoop::exec+0x1f2
000000d1`5aaff0c0 00007ff7`f64d772a     : 00007ff7`f6752d74 000000d1`5aaff500 000000d1`5aaff5c0 00000232`d22c2600 : Qt5Core!QCoreApplication::exec+0x15a
000000d1`5aaff130 00007ff7`f64d9855     : 00000000`00000000 00000232`d22b9ef0 00000232`00000000 00000232`d22c19e0 : obs64+0x3772a
000000d1`5aaff4c0 00007ff7`f6662214     : 00000000`00000000 00000000`00000000 00000000`00000000 00000232`d22aff60 : obs64+0x39855
000000d1`5aaff690 00007ff7`f6661a4a     : 00000000`00000001 00000000`00000000 00000000`00000000 00000000`00000000 : obs64+0x1c2214
000000d1`5aaff720 00007ffb`8ac57bd4     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : obs64+0x1c1a4a
000000d1`5aaff760 00007ffb`8adace51     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
000000d1`5aaff790 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21```

**Comment by Grid21** [comment] 2021-02-02 20:05
> Interesting crash dump. My WinDbg shows the crash being caused by `obs_module_ver`, but we do not even have that function implemented.
> 
> ```
> 000000d1`5aaf9818 00007ffb`881cfc21     : 000000d1`5aaf98d8 00007ffb`881e3f70 0000041f`4d8672cb 000000d1`5aaf9890 : ntdll!NtDelayExecution+0x14
> 000000d1`5aaf9820 00007ffb`721a2c5c     : 000000d1`5aaf9938 00007ffb`00000000 000000d1`c00000bb 00000000`00000000 : KERNELBASE!SleepEx+0xa1
> 000000d1`5aaf98c0 00007ffb`4dfce901     : 00000000`00989680 00000232`dcc02e60 000000d1`5aaf99d0 00007ffb`721a356f : msvcp140!_Thrd_sleep+0x3c
> 000000d1`5aaf9910 00007ffb`4dfce861     : 00000000`00989680 00000232`c1dc2d20 00000000`00000001 000000d1`5aaf9a29 : obs_websocket!obs_module_ver+0x1bfde
> 000000d1`5aaf9960 00007ffb`4e00df9a     : 00019c3a`4893e408 00000232`dcbf3000 00000232`dcbf3000 00000232`dcbf6b80 : obs_websocket!obs_module_ver+0x1bf3e
> 000000d1`5aaf9990 00007ffb`4e032d87     : 00000232`dc7b4ae0 00000232`dc76a320 00000000`0000002c 00000000`ffffffff : obs_websocket!obs_module_ver+0x5b677
> 000000d1`5aaf9a90 00007ffb`361ce33e     : 00000232`cb7e2c40 00000000`00000001 00007ffb`36563cc8 00000232`dcbf4b00 : obs_websocket!obs_module_ver+0x80464
> 000000d1`5aaf9b00 00007ffb`51152289     : 00000232`dcbf4b00 00000232`00000008 00000000`00000000 00000000`00000024 : Qt5Core!QMetaObject::activate+0x4fe
> 000000d1`5aaf9c20 00007ffb`361ce41a     : 000000d1`5aaf9d29 00007ffb`511520f0 00007ffb`36563f68 00000000`00000004 : Qt5Widgets!QDialogButtonBox::qt_static_metacall+0x199
> 000000d1`5aaf9c70 00007ffb`510b9397     : 00000232`dcbf3d40 00000232`00000009 00000232`dc76b080 00000232`00000008 : Qt5Core!QMetaObject::activate+0x5da
> 000000d1`5aaf9d90 00007ffb`510b92c1     : 00000232`dc76b000 00000232`dc76b080 00000232`dcbf3d40 00000014`00000035 : Qt5Widgets!QAbstractButton::clicked+0xa7
> 000000d1`5aaf9dd0 00007ffb`510b9fcc     : 00007ffb`50fc0000 000000d1`5aaf9f30 000000d1`5aafac70 00000233`521bd6e0 : Qt5Widgets!QAbstractButton::click+0x191
> 000000d1`5aaf9e00 00007ffb`50ffd0c7     : 00000013`00000019 00007ffb`50fc0000 000000d1`5aafac70 00000232`dcbf3d40 : Qt5Widgets!QAbstractButton::mouseReleaseEvent+0x8c
> 000000d1`5aaf9e30 00007ffb`50fd890d     : 00000232`d22de330 00000232`d22de330 00000232`dcbf3d40 000000d1`5aafac70 : Qt5Widgets!QWidget::event+0xe7
> 000000d1`5aafa180 00007ffb`50fd6419     : 00000232`dcbf3d40 000000d1`5aafa2b0 000000d1`5aafac70 00000000`00000000 : Qt5Widgets!QApplicationPrivate::notify_helper+0x17d
> 000000d1`5aafa1b0 00007ffb`361ac2c9     : 00000232`dcbf3d40 00000232`dcbf3d40 000000d1`5aafac70 00000232`dc76b080 : Qt5Widgets!QApplication::notify+0x7f9
> 000000d1`5aafa8a0 00007ffb`50fd9f53     : 00000000`00000000 00000232`ac4192e0 00007ffb`514da318 00000000`00000000 : Qt5Core!QCoreApplication::notifyInternal2+0xb9
> 000000d1`5aafa920 00007ffb`51028689     : 00000232`dcbf3d40 000000d1`5aafb910 00000000`00000001 000000d1`5aafaa00 : Qt5Widgets!QApplicationPrivate::sendMouseEvent+0x3f3
> 000000d1`5aafa9f0 00007ffb`51026348     : 00000232`ac4192e0 00000232`ac4192e0 00000232`dcbf3d40 00000232`dcbf3d40 : Qt5Widgets!QSizePolicy::QSizePolicy+0x2ee9
> 000000d1`5aafad90 00007ffb`50fd890d     : 00000232`d22de330 00000232`d22c9010 00000232`ac4192e0 000000d1`5aafb8e0 : Qt5Widgets!QSizePolicy::QSizePolicy+0xba8
> 000000d1`5aafaee0 00007ffb`50fd7767     : 00000232`d22de330 000000d1`5aafb010 000000d1`5aafb8e0 00000232`d22c9010 : Qt5Widgets!QApplicationPrivate::notify_helper+0x17d
> 000000d1`5aafaf10 00007ffb`361ac2c9     : 00000000`00000000 00000232`ac4192e0 000000d1`5aafb8e0 00000000`000d1d90 : Qt5Widgets!QApplication::notify+0x1b47
> 000000d1`5aafb600 00007ffb`4ffc0557     : 00000000`00000003 00000000`00000107 00000000`00000003 00000000`00000000 : Qt5Core!QCoreApplication::notifyInternal2+0xb9
> 000000d1`5aafb680 00007ffb`4ffa4d3d     : 00000232`91fd9690 00000000`00000000 00000000`00000000 00000232`00000107 : Qt5Gui!QGuiApplicationPrivate::processMouseEvent+0x6f7
> 000000d1`5aafbad0 00007ffb`361f82e6     : 00000232`d22ea8c0 00000000`00000000 00007ffb`503b4aa0 00007ffb`503b4aa0 : Qt5Gui!QWindowSystemInterface::sendWindowSystemEvents+0x1cd
> 000000d1`5aafbb40 00007ffb`8a0c5c7d     : 00000000`0089115e 00007ffb`8a0d20d3 00000000`00000001 00000000`00000001 : Qt5Core!QEventDispatcherWin32::processEvents+0xce6
> 000000d1`5aafbc80 00007ffb`8a0c5672     : 00000232`d2999a60 00007ffb`361f7ef0 00000000`00e80d68 000000d1`5aafbec8 : user32!UserCallWinProcCheckWow+0x2bd
> 000000d1`5aafbe10 00007ffb`361f7baf     : 00007ffb`361f7ef0 00000000`00000001 00000232`d22ea9b8 00000232`d22ea900 : user32!DispatchMessageWorker+0x1e2
> 000000d1`5aafbe90 00007ffb`6afaaa69     : 00007ff7`f6699201 00000000`00000000 00000232`d22de300 00000232`abf94600 : Qt5Core!QEventDispatcherWin32::processEvents+0x5af
> 000000d1`5aaff010 00007ffb`361a7442     : 00000000`00000000 000000d1`00000014 00000232`abf946c0 00000232`d22af6d0 : qwindows!qt_plugin_query_metadata+0x1b39
> 000000d1`5aaff040 00007ffb`361aab3a     : 00000232`d2295130 00000000`00000000 000000d1`5aaff5c0 00007ffb`362a7f98 : Qt5Core!QEventLoop::exec+0x1f2
> 000000d1`5aaff0c0 00007ff7`f64d772a     : 00007ff7`f6752d74 000000d1`5aaff500 000000d1`5aaff5c0 00000232`d22c2600 : Qt5Core!QCoreApplication::exec+0x15a
> 000000d1`5aaff130 00007ff7`f64d9855     : 00000000`00000000 00000232`d22b9ef0 00000232`00000000 00000232`d22c19e0 : obs64+0x3772a
> 000000d1`5aaff4c0 00007ff7`f6662214     : 00000000`00000000 00000000`00000000 00000000`00000000 00000232`d22aff60 : obs64+0x39855
> 000000d1`5aaff690 00007ff7`f6661a4a     : 00000000`00000001 00000000`00000000 00000000`00000000 00000000`00000000 : obs64+0x1c2214
> 000000d1`5aaff720 00007ffb`8ac57bd4     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : obs64+0x1c1a4a
> 000000d1`5aaff760 00007ffb`8adace51     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
> 000000d1`5aaff790 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21```
> ```

So what does that mean for me? What am I suppose to do? Because even people on the OBS Discord said that Websocket was "hanging on thread" which I guess this log shows that?

**Comment by Grid21** [comment] 2021-02-05 20:10
> Interesting crash dump. My WinDbg shows the crash being caused by `obs_module_ver`, but we do not even have that function implemented.
> 
> ```
> 000000d1`5aaf9818 00007ffb`881cfc21     : 000000d1`5aaf98d8 00007ffb`881e3f70 0000041f`4d8672cb 000000d1`5aaf9890 : ntdll!NtDelayExecution+0x14
> 000000d1`5aaf9820 00007ffb`721a2c5c     : 000000d1`5aaf9938 00007ffb`00000000 000000d1`c00000bb 00000000`00000000 : KERNELBASE!SleepEx+0xa1
> 000000d1`5aaf98c0 00007ffb`4dfce901     : 00000000`00989680 00000232`dcc02e60 000000d1`5aaf99d0 00007ffb`721a356f : msvcp140!_Thrd_sleep+0x3c
> 000000d1`5aaf9910 00007ffb`4dfce861     : 00000000`00989680 00000232`c1dc2d20 00000000`00000001 000000d1`5aaf9a29 : obs_websocket!obs_module_ver+0x1bfde
> 000000d1`5aaf9960 00007ffb`4e00df9a     : 00019c3a`4893e408 00000232`dcbf3000 00000232`dcbf3000 00000232`dcbf6b80 : obs_websocket!obs_module_ver+0x1bf3e
> 000000d1`5aaf9990 00007ffb`4e032d87     : 00000232`dc7b4ae0 00000232`dc76a320 00000000`0000002c 00000000`ffffffff : obs_websocket!obs_module_ver+0x5b677
> 000000d1`5aaf9a90 00007ffb`361ce33e     : 00000232`cb7e2c40 00000000`00000001 00007ffb`36563cc8 00000232`dcbf4b00 : obs_websocket!obs_module_ver+0x80464
> 000000d1`5aaf9b00 00007ffb`51152289     : 00000232`dcbf4b00 00000232`00000008 00000000`00000000 00000000`00000024 : Qt5Core!QMetaObject::activate+0x4fe
> 000000d1`5aaf9c20 00007ffb`361ce41a     : 000000d1`5aaf9d29 00007ffb`511520f0 00007ffb`36563f68 00000000`00000004 : Qt5Widgets!QDialogButtonBox::qt_static_metacall+0x199
> 000000d1`5aaf9c70 00007ffb`510b9397     : 00000232`dcbf3d40 00000232`00000009 00000232`dc76b080 00000232`00000008 : Qt5Core!QMetaObject::activate+0x5da
> 000000d1`5aaf9d90 00007ffb`510b92c1     : 00000232`dc76b000 00000232`dc76b080 00000232`dcbf3d40 00000014`00000035 : Qt5Widgets!QAbstractButton::clicked+0xa7
> 000000d1`5aaf9dd0 00007ffb`510b9fcc     : 00007ffb`50fc0000 000000d1`5aaf9f30 000000d1`5aafac70 00000233`521bd6e0 : Qt5Widgets!QAbstractButton::click+0x191
> 000000d1`5aaf9e00 00007ffb`50ffd0c7     : 00000013`00000019 00007ffb`50fc0000 000000d1`5aafac70 00000232`dcbf3d40 : Qt5Widgets!QAbstractButton::mouseReleaseEvent+0x8c
> 000000d1`5aaf9e30 00007ffb`50fd890d     : 00000232`d22de330 00000232`d22de330 00000232`dcbf3d40 000000d1`5aafac70 : Qt5Widgets!QWidget::event+0xe7
> 000000d1`5aafa180 00007ffb`50fd6419     : 00000232`dcbf3d40 000000d1`5aafa2b0 000000d1`5aafac70 00000000`00000000 : Qt5Widgets!QApplicationPrivate::notify_helper+0x17d
> 000000d1`5aafa1b0 00007ffb`361ac2c9     : 00000232`dcbf3d40 00000232`dcbf3d40 000000d1`5aafac70 00000232`dc76b080 : Qt5Widgets!QApplication::notify+0x7f9
> 000000d1`5aafa8a0 00007ffb`50fd9f53     : 00000000`00000000 00000232`ac4192e0 00007ffb`514da318 00000000`00000000 : Qt5Core!QCoreApplication::notifyInternal2+0xb9
> 000000d1`5aafa920 00007ffb`51028689     : 00000232`dcbf3d40 000000d1`5aafb910 00000000`00000001 000000d1`5aafaa00 : Qt5Widgets!QApplicationPrivate::sendMouseEvent+0x3f3
> 000000d1`5aafa9f0 00007ffb`51026348     : 00000232`ac4192e0 00000232`ac4192e0 00000232`dcbf3d40 00000232`dcbf3d40 : Qt5Widgets!QSizePolicy::QSizePolicy+0x2ee9
> 000000d1`5aafad90 00007ffb`50fd890d     : 00000232`d22de330 00000232`d22c9010 00000232`ac4192e0 000000d1`5aafb8e0 : Qt5Widgets!QSizePolicy::QSizePolicy+0xba8
> 000000d1`5aafaee0 00007ffb`50fd7767     : 00000232`d22de330 000000d1`5aafb010 000000d1`5aafb8e0 00000232`d22c9010 : Qt5Widgets!QApplicationPrivate::notify_helper+0x17d
> 000000d1`5aafaf10 00007ffb`361ac2c9     : 00000000`00000000 00000232`ac4192e0 000000d1`5aafb8e0 00000000`000d1d90 : Qt5Widgets!QApplication::notify+0x1b47
> 000000d1`5aafb600 00007ffb`4ffc0557     : 00000000`00000003 00000000`00000107 00000000`00000003 00000000`00000000 : Qt5Core!QCoreApplication::notifyInternal2+0xb9
> 000000d1`5aafb680 00007ffb`4ffa4d3d     : 00000232`91fd9690 00000000`00000000 00000000`00000000 00000232`00000107 : Qt5Gui!QGuiApplicationPrivate::processMouseEvent+0x6f7
> 000000d1`5aafbad0 00007ffb`361f82e6     : 00000232`d22ea8c0 00000000`00000000 00007ffb`503b4aa0 00007ffb`503b4aa0 : Qt5Gui!QWindowSystemInterface::sendWindowSystemEvents+0x1cd
> 000000d1`5aafbb40 00007ffb`8a0c5c7d     : 00000000`0089115e 00007ffb`8a0d20d3 00000000`00000001 00000000`00000001 : Qt5Core!QEventDispatcherWin32::processEvents+0xce6
> 000000d1`5aafbc80 00007ffb`8a0c5672     : 00000232`d2999a60 00007ffb`361f7ef0 00000000`00e80d68 000000d1`5aafbec8 : user32!UserCallWinProcCheckWow+0x2bd
> 000000d1`5aafbe10 00007ffb`361f7baf     : 00007ffb`361f7ef0 00000000`00000001 00000232`d22ea9b8 00000232`d22ea900 : user32!DispatchMessageWorker+0x1e2
> 000000d1`5aafbe90 00007ffb`6afaaa69     : 00007ff7`f6699201 00000000`00000000 00000232`d22de300 00000232`abf94600 : Qt5Core!QEventDispatcherWin32::processEvents+0x5af
> 000000d1`5aaff010 00007ffb`361a7442     : 00000000`00000000 000000d1`00000014 00000232`abf946c0 00000232`d22af6d0 : qwindows!qt_plugin_query_metadata+0x1b39
> 000000d1`5aaff040 00007ffb`361aab3a     : 00000232`d2295130 00000000`00000000 000000d1`5aaff5c0 00007ffb`362a7f98 : Qt5Core!QEventLoop::exec+0x1f2
> 000000d1`5aaff0c0 00007ff7`f64d772a     : 00007ff7`f6752d74 000000d1`5aaff500 000000d1`5aaff5c0 00000232`d22c2600 : Qt5Core!QCoreApplication::exec+0x15a
> 000000d1`5aaff130 00007ff7`f64d9855     : 00000000`00000000 00000232`d22b9ef0 00000232`00000000 00000232`d22c19e0 : obs64+0x3772a
> 000000d1`5aaff4c0 00007ff7`f6662214     : 00000000`00000000 00000000`00000000 00000000`00000000 00000232`d22aff60 : obs64+0x39855
> 000000d1`5aaff690 00007ff7`f6661a4a     : 00000000`00000001 00000000`00000000 00000000`00000000 00000000`00000000 : obs64+0x1c2214
> 000000d1`5aaff720 00007ffb`8ac57bd4     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : obs64+0x1c1a4a
> 000000d1`5aaff760 00007ffb`8adace51     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
> 000000d1`5aaff790 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21```
> ```

Hey, I had another crash caused by OBS WebSocket. And it's getting pretty serious because now OBS is hanging more than normal and won't even close properly like it's supposed to. Here is the crash file.
[Crash 2021-02-05 01-16-59.txt](https://github.com/Palakis/obs-websocket/files/5935020/Crash.2021-02-05.01-16-59.txt)

Also here are my OBS Log files too.

[2021-02-05 01-34-27.txt](https://github.com/Palakis/obs-websocket/files/5935028/2021-02-05.01-34-27.txt)
[2021-02-05 01-18-25.txt](https://github.com/Palakis/obs-websocket/files/5935029/2021-02-05.01-18-25.txt)
[2021-02-05 01-17-49.txt](https://github.com/Palakis/obs-websocket/files/5935030/2021-02-05.01-17-49.txt)

**Comment by tt2468** [comment] 2021-06-12 11:42
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks

**Closed by tt2468** 2021-06-12 11:42 UTC
