### ISSUE TITLE
[CRASH] Enabling studio mode leads to crash

### ISSUE THREAD

**Issue by iarspider** [Palakis/obs-websocket#455] opened 2020-04-01 20:43 UTC
##### Issue type
Crash report

##### Description
Changing studio mode leads to crash

##### Steps to reproduce and other useful info
*If it's a bug, please describe the steps to reproduce it and PLEASE include an OBS log file. Otherwise, remove this section.*

1. Enable studio mode with `EnableStudioMode` request (same issue with `ToggleStudioMode`)
2. Observe: "stuidio mode" button in OBS is toggled, but second preview pane is not displayed
3. Press "Studio mode" in OBS
4. Crash!

Crash report: https://obsproject.com/logs/y-UJfGwFFaUoP1Z6

##### Technical information
- **Operating System** : Windows 10 version 1909
- **OBS Studio version** : 25.0.1
- **OBS Websocket version**: 4.7.0

**Comment by Palakis** [comment] 2020-04-01 20:47
Duplicate of #389. This has been fixed in #434.

**Comment by Palakis** [comment] 2020-04-01 20:49
@iarspider This will be released in obs-websocket 4.8.0. If you depend on that feature, I can provide you a test build.

**Closed by Palakis** 2020-04-01 20:49 UTC

**Comment by iarspider** [comment] 2020-04-01 20:57
@Palakis yes please! You can send it to (my github name).at.gmail.com

**Comment by Palakis** [comment] 2020-04-01 21:05
@iarspider Grab it here: https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1032&view=artifacts&type=publishedArtifacts
