### ISSUE TITLE
Feature request: Command to Exit OBS

### ISSUE THREAD

**Issue by afriza** [Palakis/obs-websocket#521] opened 2020-05-24 16:53 UTC
##### Issue type
Feature request

##### Description
It is easy to start OBS via command line/script, but to exit OBS, I need to do this using OS's kill signal feature.. However by using kill, OBS doesn't exit cleanly and my obs-websocket client doesn't get notified with "Exiting" event and doesn't handle this event nicely..

As to why I need to exit OBS via websocket, the decklink input currently loses its sound every 2.5 days and I need to periodically restart OBS during night time..

**Comment by tt2468** [comment] 2020-05-24 17:40
Duplicate of #511 and currently not possible, sorry.

**Closed by tt2468** 2020-05-24 17:40 UTC
