### ISSUE TITLE
Remote Audio Vu-meter

### ISSUE THREAD

**Issue by PurpleHorrorRus** [Palakis/obs-websocket#198] opened 2018-03-18 07:05 UTC
##### Issue type
Feature request

##### Description
It would be nice if you could monitor, for example, the level of the microphone when I speak. If this already exists or such a request has already been, sorry for this and my bad English.

**Comment by Palakis** [comment] 2020-03-29 14:32
Depends on #275

**Comment by tt2468** [comment] 2020-05-14 11:39
Duplicate of #152

**Closed by tt2468** 2020-05-14 11:39 UTC
Labels: depends-on-obs-changes, duplicate, feature
