### ISSUE TITLE
Feature request: VolumeChanged event

### ISSUE THREAD

**Issue by XBase-xOR** [Palakis/obs-websocket#89] opened 2017-06-16 01:33 UTC
#### Issue type
Feature request

#### Description
Can we please get the VolumeChanged event from [OBS Remote](https://github.com/simplesmiler/py-obsremote/blob/master/protocol-notes.txt)?
Right now it seems I will have to constantly poll myself using GetVolume() which isn't ideal.

#### Technical information
- **Operating System** : Windows 10 with Creators Update
- **OBS Studio version** : 18.0.1

**Comment by Palakis** [comment] 2017-06-17 16:50
Kind of a duplicate of #75, so I'm closing this issue. You can contribute to the discussion there.

**Closed by Palakis** 2017-06-17 16:51 UTC
Labels: feature
