### ISSUE TITLE
obs-websocket.so requires version 5.11.0 or later, but QtWidgets provides version 5.10.0

### ISSUE THREAD

**Issue by davidhopson** [Palakis/obs-websocket#239] opened 2018-09-24 14:55 UTC
##### Issue type
It's a sort of Bug - about a library version problem

##### Description
OBS can't load obs-websocket.so

##### Steps to reproduce and other useful info
I open OBS and get the lines below in the log - this prevents me using an android app called Stream Copilot through which I can control OBS remotely

##### Technical information
- **Operating System** : MacOS 10.13.6
- **OBS Studio version** : 22.0.3
- **Log reports** :
08:06:31.011: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so->/Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so, 1): Library not loaded: @rpath/QtWidgets
08:06:31.011:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so
08:06:31.011:   Reason: Incompatible library version: obs-websocket.so requires version 5.11.0 or later, but QtWidgets provides version 5.10.0
08:06:31.011: 
08:06:31.011: Module '/Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so' not loaded

**Comment by naychrist** [comment] 2018-09-24 23:06
duplicate of #238 (more info there)

**Comment by davidhopson** [comment] 2018-09-25 11:05
> duplicate of #238 (more info there)

Missed that! Not nearly skilled enough to assist in resolving the issue. Hope someone can soon. It was so useful when it worked!

**Comment by PatTheMav** [comment] 2018-10-22 13:31
@davidhopson Building a version yourself is not an option?

**Closed** 2018-10-23 11:20 UTC
