### ISSUE TITLE
[Bug] Crash on Startup in MacOS High Sierra

### ISSUE THREAD

**Issue by DungFu** [Palakis/obs-websocket#186] opened 2018-02-11 12:07 UTC
##### Issue type
Bug report

##### Description
obs-websocket causes OBS Studio to crash on startup. Is anyone else seeing this issue as well?
Stack trace: https://pastebin.com/j3rgqFr5

##### Steps to reproduce and other useful info
Install obs-websocket and start OBS Studio and see that is crashes on startup.

##### Technical information
- MacOS High Sierra 10.13.3
- OBS Studio 21.0.2
- obs-websocket 4.3.1

**Comment by quickreactor** [comment] 2018-02-13 03:24
Same thing here. Installing 4.30 didn't help

**Comment by BossOfGames** [comment] 2018-02-14 05:32
Same issue as well. I am looking into the code right now. I may be able to contribute a patch here if it's not too deep. From what it looks like, it's almost on QT's end, however the issue is that it worked fine in the previous release.

**Comment by BossOfGames** [comment] 2018-02-14 06:08
So let me update everyone on the issue and then head to bed. Upon compiling from source via macOS, I encountered a couple notable warnings in cmake which has resulted in error outs. They are as follows

```
Utils.cpp:44:19: warning: ISO C++11 does not allow conversion from
      string literal to 'char *' [-Wwritable-strings]
WSEvents.cpp:54:43: warning: format specifies type 'int' but the
      argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
WSEvents.cpp:54:33: warning: format specifies type 'int' but the
      argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
WSEvents.cpp:54:20: warning: format specifies type 'int' but the
      argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
WSEvents.cpp:54:9: warning: format specifies type 'int' but the
      argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
```

This is a small set of the errors. The real error I am stumped on at the current moment is in regards to ```
make[1]: *** [CMakeFiles/obs-websocket.dir/all] Error 2
make: *** [all] Error 2
```
If anyone can continue to look at this, that would be awesome.

**Comment by BossOfGames** [comment] 2018-02-14 15:36
Ok, now I think I have this hammered down. Do a fresh install of OBS and it should resolve the issue. It did for me.

**Comment by haganbmj** [comment] 2018-02-14 17:28
So no changes, no rebuild, just a clean obs install worked? That's bizarre. 

The type warnings have been there forever and shouldn't be impactful, not sure what the Error 2 relates to.

**Comment by BossOfGames** [comment] 2018-02-15 04:17
Yeah I have been trying to figure out the Error 2 issue as well. That was fixed by re-downloading the repo. Apparently something is funny with the build process.

**Comment by ErikBorra** [comment] 2018-04-30 15:39
Clean install of obs worked for me too.

**Comment by dtcooper** [comment] 2018-06-12 18:07
Potential dupe of #195.

**Closed** 2019-01-01 17:31 UTC
Labels: bug
