### ISSUE TITLE
from-scene and to-scene in TransitionBegin are always empty strings when "Duplicate Scenes" is enabled

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#259] opened 2018-12-20 01:06 UTC
##### Issue type
Bug report 🐛 

##### Description
`from-scene` and `to-scene` properties of the `TransitionBegin` event are always empty strings when "Duplicate Scenes" is enabled.

##### Steps to reproduce and other useful info
Turn on the "Duplicate Scenes" feature. Then, perform a scene transition and inspect the data emitted with the `TransitionBegin` event. Observe that `from-scene` and `to-scene` are always an empty string.

##### Technical information
- **Operating System** : Win 10 Pro x64
- **OBS Studio version** : 22.0.2

**Comment by Lange** [comment] 2019-06-17 03:44
This is still present in OBS Studio 23.2.1 and `obs-websocket` 4.6.1.

**Comment by Palakis** [comment] 2019-08-31 16:08
@Lange I found the root cause of this: when "Duplicate Scenes" is checked, the duplicates are created without a name: https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main-transitions.cpp#L321

**Comment by Palakis** [comment] 2019-08-31 16:10
I'll try to see if I can find a workaround for this on my end.

**Comment by Lange** [comment] 2020-02-06 19:46
I see that a commit was landed to OBS which populates the names of these duplicate scenes: https://github.com/obsproject/obs-studio/commit/5156de4b173f3b38ee0a778425c0b01dd633da90#diff-0d4c49ee9b86534945736d6379581add

However, it seems that as of `obs-websocket` 4.7, this issue still persists. Maybe something in `obs-websocket` needs to be updated to look at this new data?

**Comment by Lange** [comment] 2020-02-06 22:07
Oh I see, OBS 24.0.3 did not include this commit, so we need to wait for the next release.

**Comment by Palakis** [comment] 2020-04-15 08:27
Should be fixed in OBS v25

**Closed by Palakis** 2020-04-15 08:27 UTC
Labels: bug, depends-on-obs-changes
