### ISSUE TITLE
OBS crashes after calling ToggleStudioMode/EnableStudioMode

### ISSUE THREAD

**Issue by BarRaider** [Palakis/obs-websocket#389] opened 2019-11-15 07:01 UTC
##### Issue type
Bug report (obs-websocket 4.7.0 with OBS Studio 24.0.3 - 64 bit)

##### Description
When trying to call EnableStudioMode or ToggleStudioMode the OBS screen flickers but does not actually move into Studio Mode. However, the "Studio Mode" button in OBS *is* enabled. Trying to press the Studio Mode button again to disable it OR trying to call ToggleStudioMode/DisableStudioMode from obs-websocket will cause a crash.
Crash seems to be related to qt5widgets.dll

##### Steps to reproduce and other useful info
*If it's a bug, please describe the steps to reproduce it and PLEASE include an OBS log file. Otherwise, remove this section.*
1. Call EnableStudioMode() or ToggleStudioMode() in obs-websocket-dotnet
-or- Send a request-type of "ToggleStudioMode" or "EnableStudioMode" to obs-websocket
2. Try to click the "Studio Mode" button in OBS
3. Crash

##### Technical information
- **Operating System** : Windows 10 1903 64 bit
- **OBS Studio version** : 24.0.3 64 bit

##### Development Environment
Using both obs-websocket and obs-websocket-dotnet. No issues with compilation.

**Comment by BarRaider** [comment] 2020-01-26 04:26
Hi,
Just checking back on this, I see it was targeted for 4.7.1 - any idea when this will be released?

**Comment by BarRaider** [comment] 2020-02-20 04:16
Trying again:
4.7.1 milestone seems empty, is this targeted to 4.7.1 or 4.8

**Comment by mknooihuisen** [comment] 2020-02-23 08:17
Doesn't this bug belong in the 4.8 Milestone @Palakis , since it looks like the 4.7.1 release has scrapped?

**Comment by Palakis** [comment] 2020-03-09 16:12
@mknooihuisen @BarRaider This was fixed in 4.7.1 indeed. Forgot to properly close it when it was released.

**Comment by Palakis** [comment] 2020-03-15 21:27
Managed to reproduce the bug, lifting the "investigation needed" label away.

**Comment by mknooihuisen** [comment] 2020-03-17 21:39
Thanks for working on this @Palakis!

**Closed** 2020-03-18 00:07 UTC
Labels: bug, important
