### ISSUE TITLE
Need feature: change CBR value

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#226] opened 2018-06-25 05:04 UTC
Hi!

I'm running a 24/7 youtube webcam. For the most part of the day there are no people in the camera and the image doesn't change much, so the 2500 kbps bitrate is good for it. However, when there are people in the camera, I would like to increase the bitrate to 5000 kbps.

I already have the system which detects people, but have no way of changing the CBR value of the stream. Could you consider adding this option to the websocket?

Stream is here:

https://www.youtube.com/watch?v=uZjstIiRbUs
![image](https://user-images.githubusercontent.com/941973/41831208-e1c916a8-786f-11e8-84a8-afa6b0bb151d.png)

Thank you!

**Comment by Palakis** [comment] 2019-08-26 22:38
Duplicate of #213

**Closed by Palakis** 2019-08-26 22:38 UTC
Labels: duplicate
