### ISSUE TITLE
Feature request: New event emiter for audio vu metter

### ISSUE THREAD

**Issue by iveinsomnia** [Palakis/obs-websocket#558] opened 2020-07-10 00:01 UTC
Working on MIDI controler (MAKI / X-Touch) soft for OBS
I was wondering if it could possible to get the Audio VU Metter data emited as an event flow or something.
I admit I don't know how it work in the code or how it is hard to handle.
Even if the emiter can be only occasional to avoid big continued flow of data, at least it could send data when it peak over -10db (in the red)

**Comment by tt2468** [comment] 2020-07-10 00:30
This is a duplicate of #152

**Closed by tt2468** 2020-07-10 00:30 UTC
